name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-rule-format:
    runs-on: ubuntu-latest
    needs: [validate-lint]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio

      - name: Check rule format with pytest
        run: |
          pytest -v -s ./test/check_rule_format.py
